### ISSUE TITLE
All_feature.txt -> Which column is which metric

### ISSUE THREAD

**Issue by eddiemorris135** [Professor-G/MicroLIA#10]
Hi All,

Thanks for sharing this program. I am curious how to ascertain which column in the all_features.txt corresponds to the calculated statistic metrics
For example, how the elements of this directory dir(training_set.extract_features.features) corresponds to the all_features.txt file?

Kind Regards
Ed

**Comment by Professor-G** [comment]
the all_features text file contains a comment line on the top with the metric names, a CSV file is also saved now when creating the simulated training set which can be used to directly load the data to the model. Please see the updated example, refresh the browser page if the content does not update: https://microlia.readthedocs.io/en/latest/source/Examples.html
