### ISSUE TITLE
TypeError: hyper_opt() got an unexpected keyword argument 'limit_search'

### ISSUE THREAD

**Issue by eddiemorris135** [Professor-G/MicroLIA#11]
I get the following error when I run through Example: OGLE II

model = models.Classifier(data_x, data_y, clf='rf')
model.create()
Imputing data...
Running feature selection...
  0%|          | 0/50 [00:00<?, ?it/s]
Feature selection complete, 79 selected out of 148!
Traceback (most recent call last):

  File "C:\Users\edmun\AppData\Local\Temp\ipykernel_6260\41337179.py", line 2, in <module>
    model.create()

  File "C:\ProgramData\Anaconda3\lib\site-packages\MicroLIA\models.py", line 186, in create
    self.model, self.best_params, self.optimization_results = hyper_opt(data_x, self.data_y, clf=self.clf, n_iter=self.n_iter,

TypeError: hyper_opt() got an unexpected keyword argument 'limit_search'

**Comment by eddiemorris135** [comment]
Cool. Look forward to it. Thanks in advance.

**Comment by eddiemorris135** [comment]
Hi Professor-G
Any chance to look at the update?
Thanks 
Ed

**Comment by Professor-G** [comment]
The code has been updated with the models module now re-named to ensemble_model

The optimization routine is sluggish on my machine so for the time being I recommend optimize=False, until version 2 release. Note no pip update has been released, please clone the repo and do pip install .

**Comment by eddiemorris135** [comment]
Iv had trouble installing the clone via anaconda (conda install).
would a standard pip install on a new machine work to reflect the new update (without anaconda)?
