### ISSUE TITLE
ImportError: cannot import name '_check_weights' from 'sklearn.neighbors._base'

### ISSUE THREAD

**Issue by eddiemorris135** [Professor-G/MicroLIA#13]
I still cannot run MicroLIA due to above error...

according to https://github.com/glemaitre

"The issue is probably linked with the version of scikit-learn required by missingpy:

https://github.com/epsilon-machine/missingpy/blob/master/requirements.txt

This version is too old. Be aware that scikit-learn is providing a KNNImputer and you don't need missingpy anymore. This package seems unmaintained."

Does it make sense to bypass missingpy?

Best Regards
Ed

**Comment by Professor-G** [comment]
Thanks for checking Ed I confirmed your findings. I updated the code significantly in prep for version 2. I just pip version 1.9.9, please pip install MicroLIA and if any bugs let me know. Only issue i am facing now is slow optimization time

doc is updated as well: https://microlia.readthedocs.io/en/latest/source/Examples.html#ensemble-classification-engine

**Comment by Professor-G** [comment]
missingpy dep removed

**Comment by Professor-G** [comment]
missingpy dep removed
