### ISSUE TITLE
ImportError: cannot import name 'MissForest_imputation' from 'MicroLIA.optimization'

### ISSUE THREAD

**Issue by eddiemorris135** [Professor-G/MicroLIA#14]
I successfully installed MicroLIA-2.0.1 however I get the following error

 from MicroLIA import models
Traceback (most recent call last):

  File "C:\Users\edmun\AppData\Local\Temp\ipykernel_22544\1682702994.py", line 1, in <module>
    from MicroLIA import models

  File "C:\Users\edmun\.conda\envs\MicroLIA\lib\site-packages\MicroLIA\models.py", line 25, in <module>
    from MicroLIA.optimization import hyper_opt, borutashap_opt, KNN_imputation, MissForest_imputation

ImportError: cannot import name 'MissForest_imputation' from 'MicroLIA.optimization' (C:\Users\edmun\.conda\envs\MicroLIA\lib\site-packages\MicroLIA\optimization.py)

My version of scikit-learn is 1.1.1. Not sure if the problem is on my side...?

regards
Ed

**Comment by Professor-G** [comment]
I changed the code such that the models.py module is now called ensemble_model.py

The error you provide still refers the models.py, could you try a clean install of the program? The error relates to the MissForest imputation algorithm, which has been removed as per your findings. If this doesn't work please let me know, I am keen you get you started on the program

**Comment by Professor-G** [comment]
This is the updated documentation, which contains information about the new feature which saves the simulated lightcurve features in a csv file for easy access and model loading: https://microlia.readthedocs.io/en/latest/source/Examples.html#training-set

**Comment by eddiemorris135** [comment]
I deleted the existing virtual env and created a new one. Now its up and running. 

Many thanks for your support. Look forward to exploring the tool! :-)

**Comment by Professor-G** [comment]
code updated.
